### ISSUE TITLE
build database

### ISSUE THREAD

**Issue by krashenbern** [NSS-Day-Cohort-58/exomine-exo-man#6]
* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request

* **What is the current behavior?**
build a database of mines, minerals, minedMinerals, colonies, colonyMinerals, and governors. 
follow erd, make at least 3 options in each table

**Comment by Lorin-Jones** [comment]
database--array for minerals, governors, mines, minedminerals, colonyminerals, colonies.... customorders array, empty orderbuilder object....

**Comment by Lorin-Jones** [comment]
getter and setter functions as well as orderbuilder function which will add and clear

**Comment by krashenbern** [comment]
Database pushed and issue closed.
